DEBUG 2016-03-01 16:13:59,108: 	 Executing command: 'submit'
DEBUG 2016-03-01 16:13:59,109: 	 Found CRAB cache file /home/kskovpen/.crab3
DEBUG 2016-03-01 16:13:59,120: 	 Checking credentials
DEBUG 2016-03-01 16:13:59,120: 	 Found proxy file /tmp/x509up_u7989
DEBUG 2016-03-01 16:13:59,120: 	 Getting proxy life time left
DEBUG 2016-03-01 16:14:00,024: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u7989 -timeleft
 output : 14915

 error: 
 retcode : 0
DEBUG 2016-03-01 16:14:00,828: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u7989 -actimeleft
 output : 14913

 error: 
 retcode : 0
DEBUG 2016-03-01 16:14:00,829: 	 Proxy valid for 04:08:35 hours
INFO 2016-03-01 16:14:00,829: 	 Will use CRAB configuration file crabConfig.py
DEBUG 2016-03-01 16:14:00,829: 	 Loading CRAB configuration file.
DEBUG 2016-03-01 16:14:00,833: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-03-01 16:14:00,833: 	 Working area '/grid_mnt/home-pbs/kskovpen/bTagRun2/CMSSW_7_4_6_patch6/src/SimAnalysis/SimAnalysis/test/PROD/crab_QCD_Pt_300to470_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8_GEN_SIM' already exists 
Please change the requestName in the config file
ERROR 2016-03-01 16:14:00,833: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1602/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1602/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1602/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 32, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1602/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 299, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1602/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/grid_mnt/home-pbs/kskovpen/bTagRun2/CMSSW_7_4_6_patch6/src/SimAnalysis/SimAnalysis/test/PROD/crab_QCD_Pt_300to470_MuEnrichedPt5_TuneCUETP8M1_13TeV_pythia8_GEN_SIM' already exists 
Please change the requestName in the config file
DEBUG 2016-11-01 20:50:23,910: 	 Executing command: 'submit'
DEBUG 2016-11-01 20:50:23,911: 	 Found CRAB cache file /user/kskovpen/.crab3
DEBUG 2016-11-01 20:50:23,942: 	 Checking credentials
DEBUG 2016-11-01 20:50:23,942: 	 Found proxy file /tmp/x509up_u20657
DEBUG 2016-11-01 20:50:23,942: 	 Getting proxy life time left
DEBUG 2016-11-01 20:50:24,446: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20657 -timeleft
 output : 415511

 error: 
 retcode : 0
ERROR 2016-11-01 20:50:24,611: 	 Keyboard Interrupted
